using System;

namespace Project_Euler_PS1
{
    class EvenFibonacci
    {
        public EvenFibonacci()
        {
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: \n  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... \n By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
            Console.WriteLine();
            Console.WriteLine(Fib());
        }

        private int Fib()
        {
            int one = 1;
            int two = 2;
            int Value = 3;
            int sum = 2;
            Console.Write("1,2");
            while (Value < 4000000)
            {
                Console.Write("," + Value);
                if (Value % 2 == 0)
                    sum += Value;
                one = two;
                two = Value;
                Value = one + two;
            }
            Console.WriteLine();
            return sum;
        }
    }
}